name: cmake

on:
  push:
    branches: [master]
  schedule:
    - cron:  '0 23 * * 4'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 3.19.8

jobs:
  binary:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add build-base
          apk add \
            bzip2-dev \
            curl-dev expat-dev  \
            libarchive-dev \
            linux-headers \
            libuv-dev \
            ncurses-dev \
            rhash-dev \
            xz-dev \
            zlib-dev \
            py3-sphinx

      - name: Download source files
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${{ env.VERSION }}/cmake-${{ env.VERSION }}.tar.gz
          tar -xvf cmake-${{ env.VERSION }}.tar.gz

      - name: Compile source files
        run: |
          cd cmake-${{ env.VERSION }}
          ./bootstrap \
            --prefix=/cmake-${{ env.VERSION }} \
            --mandir=/man \
            --datadir=/share/cmake \
            --docdir=/doc/cmake \
            --sphinx-man \
            --system-libs \
            --no-system-jsoncpp
          make -j2

      - name: Package up binaries
        run: |
          cd cmake-${{ env.VERSION }}
          make DESTDIR=tmp install
          cd tmp
          tar -czvf ../../cmake-${{ env.VERSION }}.tar.gz cmake-${{ env.VERSION }}

      - name: Upload binaries package
        uses: actions/upload-artifact@v2
        with:
          name: cmake-${{ env.VERSION }}
          path: cmake-${{ env.VERSION }}.tar.gz
          retention-days: 7
